server {
    listen 8081 default_server;
    listen [::]:8081 default_server;

    server_name  _;

    root "/app/api";
    index index.php;

    rewrite ^/public/(.*)$ /public.php?u=$1 last;
    rewrite /webhook /webhook.php last;
	rewrite ^/webhook/(.*)$ /webhook.php last;

    # Pass "*.php" files to PHP-FPM
    location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    include /etc/nginx/server-opts.d/*.conf;
}